import{a as w,S as P,i as l}from"./assets/vendor-BclIaOog.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",S="52792458-b846233229dd28b7897b8b61b",M=15;async function p(i,t=1){try{const{data:o}=await w.get(B,{params:{key:S,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:M}});return o}catch(o){throw console.error("Error fetching images:",o),o}}const h=document.querySelector(".gallery"),d=document.querySelector(".loader"),m=document.getElementById("load-more"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250});f();function y(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:c,comments:E,downloads:v})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${o}" alt="${e}" loading="lazy"/>
          <div class="info">
            <p>👍 ${r}</p>
            <p>👁️ ${c}</p>
            <p>💬 ${E}</p>
            <p>⬇️ ${v}</p>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),R.refresh()}function q(){h.innerHTML=""}function b(){d.classList.remove("hidden"),d.classList.add("active")}function L(){d.classList.add("hidden"),d.classList.remove("active")}function $(){m.style.display="block"}function f(){m.style.display="none"}function O(){return h}function x(){return m}const C=document.getElementById("search-form"),F=C.querySelector('input[name="search-text"]'),H=O(),A=x();let u="",s=1,a=0;function g(){f(),l.info({icon:"fa-solid fa-ban",iconColor:"#2222",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"})}C.addEventListener("submit",async i=>{var o;i.preventDefault();const t=F.value.trim();if(!t){l.error({icon:"fa-solid fa-ban",iconColor:"#222",message:"Please enter a search term!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"});return}t!==u&&(u=t,s=1,a=0,q(),f()),b();try{const n=await p(u,s);if(!((o=n.hits)!=null&&o.length)){l.info({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Sorry, there are no images matching your search query.",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),f();return}y(n.hits),a=n.totalHits||a;const e=Math.ceil(a/15);s<e?$():g()}catch(n){l.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Something went wrong. Please try again!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),console.error(n)}finally{L()}});A.addEventListener("click",async()=>{var i;try{b();const t=s+1,o=await p(u,t);if(!((i=o.hits)!=null&&i.length)){g();return}y(o.hits),s=t,a=o.totalHits||a;const n=H.querySelector(".gallery-item");if(n){const{height:r}=n.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const e=Math.ceil(a/15);s>=e&&g()}catch(t){l.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Something went wrong. Please try again!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),console.error(t)}finally{L()}});
//# sourceMappingURL=index.js.map
