import{S as E,i as n}from"./assets/vendor-Dg3uDB0e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="https://pixabay.com/api/",C="52792458-b846233229dd28b7897b8b61b",B=15;async function m(o,r=1){try{const e=new URL(S);e.searchParams.set("key",C),e.searchParams.set("q",o),e.searchParams.set("image_type","photo"),e.searchParams.set("orientation","horizontal"),e.searchParams.set("safesearch","true"),e.searchParams.set("per_page",B.toString()),e.searchParams.set("page",String(r));const a=await fetch(e.toString());if(!a.ok)throw new Error(`HTTP error! status: ${a.status}`);return await a.json()}catch(e){throw console.error("Error fetching images:",e),e}}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.getElementById("load-more"),M=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(({webformatURL:e,largeImageURL:a,tags:t,likes:s,views:c,comments:w,downloads:v})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${e}" alt="${t}" loading="lazy"/>
          <div class="info">
            <p>👍 ${s}</p>
            <p>👁️ ${c}</p>
            <p>💬 ${w}</p>
            <p>⬇️ ${v}</p>
          </div>
        </a>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){f.innerHTML=""}function p(){h.classList.remove("hidden"),h.classList.add("active")}function b(){h.classList.add("hidden"),h.classList.remove("active")}function L(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}function q(){return f}function R(){return g}const P=document.getElementById("search-form"),H=P.querySelector('input[name="search-text"]'),O=q(),A=R();let d="",i=1,u=0;P.addEventListener("submit",async o=>{o.preventDefault();const r=H.value.trim();if(!r){n.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Please enter a search term!",backgroundColor:"#EF4040",timeout:3e3,close:!1,position:"topRight"});return}r!==d&&(d=r,i=1,$(),l());try{p();const e=await m(d,i);if(!e.hits||e.hits.length===0){n.info({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",timeout:3e3,close:!1,position:"topRight"}),l();return}y(e.hits),u=e.totalHits||0;const a=Math.ceil(u/15);i<a?L():(l(),n.info({message:"We're sorry, but you've reached the end of search results.",timeout:4e3,position:"topRight"})),i+=1}catch(e){n.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Something went wrong. Please try again!",backgroundColor:"#EF4040",timeout:3e3,close:!1,position:"topRight"}),console.error(e)}finally{b()}});A.addEventListener("click",async()=>{try{p();const o=await m(d,i);if(!o.hits||o.hits.length===0){l(),n.info({message:"We're sorry, but you've reached the end of search results."});return}y(o.hits);const r=O.querySelector(".gallery-item");if(r){const{height:a}=r.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}u=o.totalHits||u;const e=Math.ceil(u/15);i>=e?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",timeout:3e3})):L(),i+=1}catch(o){n.error({message:"Something went wrong. Please try again!"}),console.error(o)}finally{b()}});
//# sourceMappingURL=index.js.map
