import{a as E,S as B,i as c}from"./assets/vendor-BclIaOog.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="https://pixabay.com/api/",M="52792458-b846233229dd28b7897b8b61b";async function p(i,t=1){try{return(await E.get(S,{params:{key:M,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(o){throw console.error("Error fetching images:",o),o}}const h=document.querySelector(".gallery"),u=document.querySelector(".loader"),m=document.getElementById("load-more"),P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:s,comments:C,downloads:w})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${o}" alt="${e}" loading="lazy"/>
          <div class="info">
            <p>👍 ${r}</p>
            <p>👁️ ${s}</p>
            <p>💬 ${C}</p>
            <p>⬇️ ${w}</p>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function q(){h.innerHTML=""}function b(){u.classList.remove("hidden"),u.classList.add("active")}function L(){u.classList.add("hidden"),u.classList.remove("active")}function R(){m.classList.remove("hidden")}function f(){m.classList.add("hidden")}function $(){return h}function O(){return m}const v=document.getElementById("search-form"),x=v.querySelector('input[name="search-text"]'),F=$(),H=O();let l="",a=1,d=0;function g(){f(),c.info({icon:"fa-solid fa-ban",iconColor:"#2222",message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"})}v.addEventListener("submit",async i=>{var o;i.preventDefault();const t=x.value.trim();if(!t){c.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Please enter a search term!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"});return}t!==l&&(l=t,a=1,d=0,q(),f()),b();try{const n=await p(l,a);if(!((o=n.hits)!=null&&o.length)){c.info({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Sorry, there are no images matching your search query.",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),f();return}y(n.hits),d=n.totalHits||0;const e=Math.ceil(d/15);a+=1,a>e?g():R()}catch(n){c.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Something went wrong. Please try again!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),console.error(n)}finally{L()}});H.addEventListener("click",async()=>{var i;try{b(),a+=1;const t=await p(l,a);if(!((i=t.hits)!=null&&i.length)){g();return}y(t.hits);const o=F.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const n=Math.ceil(d/15);a>=n&&g()}catch(t){c.error({icon:"fa-solid fa-ban",iconColor:"#2222",message:"Something went wrong. Please try again!",backgroundColor:"#EF4040",timeout:3e3,position:"topRight"}),console.error(t)}finally{L()}});
//# sourceMappingURL=index.js.map
